# Generated by Django 2.2.28 on 2023-06-07 17:32

from django.db import migrations, models
import foodgram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230318_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=200, unique=True, validators=[foodgram.validators.validate_slug], verbose_name='Слаг'),
        ),
    ]
